# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Angular12BaseProyect

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install
       
      - name: Build Angular app
        run: |
          npm run build:ssr --if-present

      - name: Create ZIP artifact
        run: |
          zip -r angular-app.zip dist
        working-directory: ${{ github.workspace }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: angular-artifact
          path: angular-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v2
        with:
          name: angular-artifact
          path: /tmp

      - name: Unzip artifact
        run: unzip /tmp/angular-app.zip -d /tmp

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Angular12BaseProyect'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D8973261C1FE4B80A04595E238EFC68D }}
          package: /tmp

      